csv_file: "/genbank_store/max/download/results1/downloaded_sra_ids.csv"
output_directory: "/genbank_store/max/download/results1"
query_fasta: "/genbank_store/max/data/Ostreobium_query.fa"
blast_search:
    perc_identity: 90
    qcov_hsp_perc: 90
