csv_file: "/genbank_store/agata/data/SRA_list_Marcelino_firstten.csv"
output_directory: "/genbank_store/max/download/results1"
query_fasta: "/genbank_store/agata/data/Ostreobium_query.fa"
blast_search:
    perc_identity: 90
    qcov_hsp_perc: 90
